/* Copyright (c) 2018-2026 Steven Varga, steven@vargalabs.com Toronto, ON Canada */

#pragma once

// Issue #31 Phase 3 — .proto text emitter.
//
// Walks the same AST events PbTemplateCallback walks, emits a sibling
// .proto schema file. Same vocabulary (pb::field, pb::wire, pb::adapter,
// pb::ignore, pb::name, pb::doc, pb::on_missing), different output: the
// human-readable proto3 schema that any other language's protoc-derived
// generator can consume.
//
// Default name mapping: C++ struct identifier → strip trailing `_t`/
// `_type`/`_struct` + PascalCase. `event_t` → `Event`, `telemetry_event_t`
// → `TelemetryEvent`. Override via class-scope [[pb::name("Foo")]].

#include <clang/AST/Attr.h>
#include <clang/AST/Decl.h>
#include <clang/AST/DeclCXX.h>
#include <clang/AST/DeclTemplate.h>
#include <clang/AST/Type.h>
#include <clang/ASTMatchers/ASTMatchFinder.h>
#include <llvm/ADT/StringRef.h>
#include <llvm/Support/Casting.h>

#include <cctype>
#include <cstdint>
#include <fstream>
#include <optional>
#include <set>
#include <string>
#include <vector>

#include "utils.hpp"
#include "pb_attr_reader.hpp"

class ProtoTemplateCallback : public clang::ast_matchers::MatchFinder::MatchCallback {
public:
    explicit ProtoTemplateCallback(const std::string& path) : output_path(path) {}

    ~ProtoTemplateCallback() {
        // Assemble the .proto file in order: syntax → imports → package
        // → messages → trailing tooling hints. messages_buf was populated
        // during the walk so we can emit imports + package UP-FRONT
        // (proto3 requires imports to appear after `syntax = ...;` and
        // `package` to come before any message declaration).
        std::ofstream io(output_path);
        io << "// Generated by h5cpp-compiler --protocol-buffers --proto-out. Do not edit.\n";
        // Commit 2: [[pb::target_syntax(...)]] selects proto3 (default)
        // vs edition2023 (gated on libprotoc 26+). First-encountered
        // value wins across the AST walk.
        if (target_syntax == "edition2023") {
            io << "edition = \"2023\";\n";
        } else {
            io << "syntax = \"proto3\";\n";
        }
        if (!imports.empty()) io << "\n";
        for (const auto& imp : imports) {
            io << "import \"" << imp << "\";\n";
        }
        if (!package.empty()) {
            io << "\npackage " << package << ";\n";
        }
        io << "\n";
        io << messages_buf.str();
        // Commit 2: [[pb::descriptor_set_out(...)]] — record the user's
        // desired binary FileDescriptorSet output path as a trailing
        // comment + protoc invocation hint. Actual .desc emission is
        // deferred to a downstream protoc invocation (out of scope for
        // h5cpp itself, which doesn't link against libprotobuf).
        if (!descriptor_set_out.empty()) {
            io << "\n// pb::descriptor_set_out: \"" << descriptor_set_out << "\"\n";
            io << "// To produce the binary FileDescriptorSet, run:\n";
            io << "//   protoc --descriptor_set_out=" << descriptor_set_out
               << " --proto_path=. <this-file>\n";
        }
    }

    void run(const clang::ast_matchers::MatchFinder::MatchResult& result) override {
        const auto* node =
            result.Nodes.getNodeAs<clang::CXXRecordDecl>("cxxRecordDecl");
        if (!node) return;
        node = node->getDefinition();
        if (!node) return;

        // Walk dependency order: any user-defined record reachable as a
        // field's type emits FIRST so subsequent references resolve. Enums
        // reached during the walk are queued separately and emitted in
        // declaration order before the first message that references them.
        std::vector<const clang::CXXRecordDecl*> order;
        collect_deps_(node, order);
        for (const clang::EnumDecl* ed : enum_order_) {
            if (!enums_emitted_.insert(ed).second) continue;
            emit_enum_(ed);
        }
        enum_order_.clear();
        for (const clang::CXXRecordDecl* r : order) {
            if (!emitted_.insert(r).second) continue;
            // Commit 4: records marked [[pb::service("...")]] become
            // proto3 `service` blocks, not `message` blocks. Skip
            // emit_message_ entirely and emit an RPC list instead.
            if (has_attr_(r, "pb::service")) {
                emit_service_(r);
                continue;
            }
            emit_message_(r);
        }
    }

private:
    std::string output_path;
    std::ostringstream messages_buf;
    std::ostream& io = messages_buf;        // emit_* writes go through this
    std::set<const clang::CXXRecordDecl*> emitted_;
    std::set<const clang::CXXRecordDecl*> seen_for_deps_;
    std::set<const clang::EnumDecl*> enums_seen_;       // dedup queue
    std::set<const clang::EnumDecl*> enums_emitted_;    // dedup actual emission
    std::vector<const clang::EnumDecl*> enum_order_;    // emit order
    std::set<std::string> imports;          // proto3 import lines
    std::string package;                    // first-seen file-scope package
    std::string current_name_convention;    // class-level pb::name_all value
    std::string target_syntax;              // first-seen pb::target_syntax (proto3 / edition2023)
    std::string descriptor_set_out;         // first-seen pb::descriptor_set_out path

    void track_import_(const std::string& path) { imports.insert(path); }

    // ── Topological walk ─────────────────────────────────────────────────
    void collect_deps_(const clang::CXXRecordDecl* node,
                        std::vector<const clang::CXXRecordDecl*>& order) {
        if (!seen_for_deps_.insert(node).second) return;
        for (const clang::FieldDecl* fld : node->fields()) {
            const clang::QualType qt = fld->getType().getCanonicalType();
            collect_user_records_from_type_(qt, order);
            // Commit 4: if the field is std::function<R(A)>, the R and A
            // types are messages that must precede the service block.
            if (auto rpc = std_function_rpc_(fld); rpc) {
                collect_user_records_from_type_(rpc->req_qt.getCanonicalType(), order);
                collect_user_records_from_type_(rpc->resp_qt.getCanonicalType(), order);
            }
        }
        order.push_back(node);
    }

    // Commit 4: descended-from std::function<R(A)> shape — return the
    // Request and Response proto3 type names if `fld` is an RPC handler.
    struct rpc_signature {
        std::string request;
        std::string response;
        clang::QualType req_qt;
        clang::QualType resp_qt;
    };
    std::optional<rpc_signature> std_function_rpc_(const clang::FieldDecl* fld) const {
        const clang::QualType qt = fld->getType();
        const clang::Type* tp = qt.getTypePtrOrNull();
        if (!tp || !tp->isRecordType()) return std::nullopt;
        const auto* spec =
            clang::dyn_cast<clang::ClassTemplateSpecializationDecl>(tp->getAsCXXRecordDecl());
        if (!spec || !is_stdlib_record_(spec)) return std::nullopt;
        if (spec->getName() != "function") return std::nullopt;
        const auto& args = spec->getTemplateArgs();
        if (args.size() < 1 || args[0].getKind() != clang::TemplateArgument::Type)
            return std::nullopt;
        const clang::QualType fn_qt = args[0].getAsType();
        const auto* fn_proto = fn_qt->getAs<clang::FunctionProtoType>();
        if (!fn_proto) return std::nullopt;
        if (fn_proto->getNumParams() != 1) return std::nullopt;
        rpc_signature out;
        out.resp_qt  = fn_proto->getReturnType();
        out.req_qt   = fn_proto->getParamType(0);
        out.response = proto3_type_(out.resp_qt);
        out.request  = proto3_type_(out.req_qt);
        return out;
    }

    void collect_user_records_from_type_(clang::QualType qt,
                                           std::vector<const clang::CXXRecordDecl*>& order) {
        const clang::Type* tp = qt.getTypePtrOrNull();
        if (!tp) return;
        // Enum: queue the EnumDecl so emit_enum_ writes the declaration
        // BEFORE any message that references the enum by name.
        if (tp->isEnumeralType()) {
            if (const auto* et = tp->getAs<clang::EnumType>()) {
                queue_enum_(et->getDecl());
            }
            return;
        }
        if (!tp->isRecordType()) return;
        const clang::CXXRecordDecl* rec = tp->getAsCXXRecordDecl();
        if (!rec) return;
        // Skip stdlib types — they're leaves from the proto3 perspective.
        if (is_stdlib_record_(rec)) {
            // Walk their template args though, to find user types nested
            // inside std::vector<T>, std::map<K,V>, etc.
            if (const auto* spec =
                    clang::dyn_cast<clang::ClassTemplateSpecializationDecl>(rec)) {
                for (const auto& arg : spec->getTemplateArgs().asArray()) {
                    if (arg.getKind() == clang::TemplateArgument::Type) {
                        collect_user_records_from_type_(arg.getAsType(), order);
                    } else if (arg.getKind() == clang::TemplateArgument::Pack) {
                        for (const auto& packed : arg.getPackAsArray()) {
                            if (packed.getKind() == clang::TemplateArgument::Type)
                                collect_user_records_from_type_(packed.getAsType(), order);
                        }
                    }
                }
            }
            return;
        }
        collect_deps_(rec, order);
    }

    void queue_enum_(const clang::EnumDecl* ed) {
        if (!ed) return;
        const clang::EnumDecl* def = ed->getDefinition();
        if (!def) def = ed;
        if (!enums_seen_.insert(def).second) return;
        enum_order_.push_back(def);
    }

    // ── Enum emission ───────────────────────────────────────────────────
    // Emit a proto3 `enum Foo { VAL = N; ... }` block. Diagnoses a missing
    // zero-valued enumerator (proto3 requires one). The user may override
    // by adding `[[pb::enum_zero("UNSPECIFIED")]]` on the enum decl, which
    // synthesizes a zero-valued first entry with that name (the actual C++
    // enum is unchanged — the synthetic entry only exists in the .proto).
    void emit_enum_(const clang::EnumDecl* ed) {
        if (!ed) return;
        const std::string doc = read_enum_string_attr_(ed, "pb::doc");
        const std::string explicit_name = read_enum_string_attr_(ed, "pb::name");
        const std::string proto_name = !explicit_name.empty()
            ? explicit_name : default_enum_name_(ed->getNameAsString());
        const std::string zero_override = read_enum_string_attr_(ed, "pb::enum_zero");

        // Walk enumerators, check whether one already has value 0.
        std::vector<std::pair<std::string, std::int64_t>> values;
        bool has_zero = false;
        for (const clang::EnumConstantDecl* ec : ed->enumerators()) {
            const std::string name = ec->getNameAsString();
            const std::int64_t v   = ec->getInitVal().getSExtValue();
            if (v == 0) has_zero = true;
            values.push_back({ name, v });
        }

        if (!has_zero && zero_override.empty()) {
            llvm::errs() << "h5cpp-compiler --proto-out: enum '"
                          << ed->getNameAsString()
                          << "' has no 0-valued enumerator — proto3 requires one. "
                          << "Add a zero-valued entry to the C++ enum, or annotate "
                          << "the enum with `[[pb::enum_zero(\"UNSPECIFIED\")]]` to "
                          << "synthesize a zero-valued name in the .proto output.\n";
            // Continue emission anyway — the produced .proto will be invalid
            // proto3 (protoc will reject it), but downstream tools may want
            // to inspect the output to see what was attempted.
        }

        if (!doc.empty()) io << "// " << doc << "\n";
        io << "enum " << proto_name << " {\n";
        if (!has_zero && !zero_override.empty()) {
            io << "    " << zero_override << " = 0;\n";
        }
        for (const auto& [name, v] : values) {
            io << "    " << name << " = " << v << ";\n";
        }
        io << "}\n\n";
    }

    // Reader for class-level-style annotations on EnumDecls. The
    // [[pb::...]] attribute machinery attaches to the EnumDecl the same
    // way it attaches to CXXRecordDecl, so a single helper covers both.
    std::string read_enum_string_attr_(const clang::EnumDecl* ed,
                                         llvm::StringRef kind) const {
        if (!ed) return {};
        if (const auto* ann = find_annotate_(ed, kind)) return read_string_arg_(ann);
        return {};
    }

    // Strip `_e`/`_enum`/`_t`/`_type`/`_struct` + PascalCase. Same rule as
    // default_message_name_ but with the enum-specific suffixes added.
    std::string default_enum_name_(const std::string& cpp_name) const {
        std::string s = cpp_name;
        for (const char* suffix : { "_struct", "_enum", "_type", "_e", "_t" }) {
            const std::size_t n = std::strlen(suffix);
            if (s.size() > n && s.compare(s.size() - n, n, suffix) == 0) {
                s.resize(s.size() - n);
                break;
            }
        }
        std::string out;
        bool cap = true;
        for (char c : s) {
            if (c == '_') { cap = true; continue; }
            out.push_back(cap ? static_cast<char>(std::toupper(static_cast<unsigned char>(c))) : c);
            cap = false;
        }
        return out;
    }

    bool is_stdlib_record_(const clang::CXXRecordDecl* rec) const {
        for (const clang::DeclContext* ctx = rec->getDeclContext(); ctx;
             ctx = ctx->getParent()) {
            if (const auto* ns = clang::dyn_cast<clang::NamespaceDecl>(ctx)) {
                llvm::StringRef name = ns->getName();
                if (name == "std" || name == "__cxx11" || name == "__1" ||
                    name == "chrono") return true;
            }
        }
        return false;
    }

    // ── Service emission (Commit 4) ─────────────────────────────────────
    // Records marked [[pb::service("Name")]] become `service Name { ... }`
    // blocks in the .proto. Each std::function<R(A)> member emits one
    // `rpc <member-name>(A) returns (R);` line. Non-function fields are
    // skipped with a diagnostic (services are RPC-handler-only by
    // convention; data lives on the request/response messages).
    void emit_service_(const clang::CXXRecordDecl* rec) {
        const std::string service_name = read_class_string_attr_(rec, "pb::service");
        if (service_name.empty()) return;

        const std::string doc = read_class_string_attr_(rec, "pb::doc");
        if (!doc.empty()) io << "// " << doc << "\n";
        io << "service " << service_name << " {\n";
        for (const clang::FieldDecl* fld : rec->fields()) {
            if (has_attr_(fld, "pb::ignore")) continue;
            const auto rpc = std_function_rpc_(fld);
            if (!rpc) {
                llvm::errs() << "h5cpp-compiler --proto-out: service '"
                              << service_name << "' field '" << utils::name(fld)
                              << "' is not a std::function<Resp(Req)> — skipping. "
                              << "Service classes carry RPC handlers only; data lives "
                              << "on the request/response messages.\n";
                continue;
            }
            const std::string field_doc = read_field_string_attr_(fld, "pb::doc");
            if (!field_doc.empty()) io << "    // " << field_doc << "\n";
            io << "    rpc " << utils::name(fld) << "(" << rpc->request
               << ") returns (" << rpc->response << ");\n";
        }
        io << "}\n\n";
    }

    // ── Per-record emission ──────────────────────────────────────────────
    void emit_message_(const clang::CXXRecordDecl* rec) {
        // Commit 2 (Tier 4): [[pb::reject]] — skip the record entirely.
        // The .hpp shim path also skips (consumer_pb.hpp), so a rejected
        // record appears in NEITHER artifact and emits a diagnostic on
        // the pb consumer side.
        if (has_attr_(rec, "pb::reject")) return;

        // Phase 4: collect class-level metadata up-front so emit decisions
        // (naming, reserved zones, version) have full context.
        const std::string doc          = read_class_string_attr_(rec, "pb::doc");
        const std::string explicit_name = read_class_string_attr_(rec, "pb::name");
        const std::string pkg          = read_class_string_attr_(rec, "pb::package");
        const std::string name_all     = read_class_string_attr_(rec, "pb::name_all");
        const auto version_arg         = read_class_int_arg_(rec, "pb::version");
        const auto reserved_ints       = read_class_int_args_(rec, "pb::reserved");
        const auto reserved_strs       = read_class_string_args_(rec, "pb::reserved");

        // Commit 2: capture class-level file-scope tooling hints. These
        // collectively shape the file header (target_syntax) and trailer
        // (descriptor_set_out). First-encountered value wins.
        const std::string ts = read_class_string_attr_(rec, "pb::target_syntax");
        if (!ts.empty() && target_syntax.empty()) target_syntax = ts;
        const std::string dso = read_class_string_attr_(rec, "pb::descriptor_set_out");
        if (!dso.empty() && descriptor_set_out.empty()) descriptor_set_out = dso;

        // pb::package is file-level in proto3. Take the first non-empty
        // declaration seen across the AST walk; subsequent definitions of
        // the same value are fine, conflicts emit a comment marker.
        if (!pkg.empty()) {
            if (package.empty()) package = pkg;
            else if (package != pkg) {
                io << "// WARNING: pb::package conflict — \"" << pkg
                   << "\" ignored, file-scope package is \"" << package << "\"\n";
            }
        }

        // pb::name_all applies to all field names in this record. Track it
        // for the duration of emit_field_ calls.
        current_name_convention = name_all;

        // Collect pb::alias from field attributes — proto3 expresses
        // backward-name compat as `reserved "old_name";` at message scope.
        std::vector<std::string> aliases;
        for (const clang::FieldDecl* fld : rec->fields()) {
            const std::string a = read_field_string_attr_(fld, "pb::alias");
            if (!a.empty()) aliases.push_back(a);
        }

        const std::string msg_name = !explicit_name.empty()
            ? explicit_name : default_message_name_(rec->getNameAsString());

        if (!doc.empty()) io << "// " << doc << "\n";
        io << "message " << msg_name << " {\n";

        // Reserved + version preamble.
        if (!reserved_ints.empty()) {
            io << "    reserved ";
            for (std::size_t i = 0; i < reserved_ints.size(); ++i) {
                if (i) io << ", ";
                io << reserved_ints[i];
            }
            io << ";\n";
        }
        if (!reserved_strs.empty()) {
            io << "    reserved ";
            for (std::size_t i = 0; i < reserved_strs.size(); ++i) {
                if (i) io << ", ";
                io << "\"" << reserved_strs[i] << "\"";
            }
            io << ";\n";
        }
        if (!aliases.empty()) {
            io << "    reserved ";
            for (std::size_t i = 0; i < aliases.size(); ++i) {
                if (i) io << ", ";
                io << "\"" << aliases[i] << "\"";
            }
            io << ";  // pb::alias\n";
        }
        if (version_arg) {
            io << "    option (h5cpp.schema_version) = " << *version_arg << ";\n";
        }

        for (const clang::FieldDecl* fld : rec->fields()) {
            emit_field_(fld);
        }

        io << "}\n\n";
        current_name_convention.clear();
    }

    // Phase 4 + Commit 2: field-level options string built from pb::packed,
    // pb::deprecated, pb::json_name, etc. Returned as
    // " [opt = true, opt2 = "...", ...]" suffix ready to append before the
    // trailing semicolon, or empty if no options.
    std::string field_options_(const clang::FieldDecl* fld) const {
        std::vector<std::string> opts;
        if (has_attr_(fld, "pb::packed"))     opts.push_back("packed = true");
        if (has_attr_(fld, "pb::deprecated")) opts.push_back("deprecated = true");
        const std::string jn = read_field_string_attr_(fld, "pb::json_name");
        if (!jn.empty()) opts.push_back("json_name = \"" + jn + "\"");
        if (opts.empty()) return {};
        std::string out = " [";
        for (std::size_t i = 0; i < opts.size(); ++i) {
            if (i) out += ", ";
            out += opts[i];
        }
        out += "]";
        return out;
    }

    void emit_field_(const clang::FieldDecl* fld) {
        if (has_attr_(fld, "pb::ignore")) {
            // Don't emit ignored members to .proto.
            return;
        }

        const clang::QualType qt = fld->getType();
        const std::string field_name = field_proto_name_(fld);
        const std::string field_doc  = read_field_string_attr_(fld, "pb::doc");
        const std::string options    = field_options_(fld);

        // std::variant → oneof
        if (is_std_variant_(qt)) {
            emit_oneof_(fld);
            return;
        }

        // std::map / std::unordered_map → map<K,V>
        if (auto kv = std_map_kv_(qt); kv) {
            const auto tags = read_field_int_args_(fld, "pb::field");
            if (tags.size() != 1) return;   // diagnostic handled by pb consumer
            if (!field_doc.empty()) io << "    // " << field_doc << "\n";
            io << "    map<" << proto3_type_(kv->first)
               << ", " << proto3_type_(kv->second) << "> "
               << field_name << " = " << tags[0] << options << ";\n";
            return;
        }

        // std::vector<T> → repeated T
        if (auto inner = std_vector_inner_(qt); inner) {
            const auto tags = read_field_int_args_(fld, "pb::field");
            if (tags.size() != 1) return;
            if (!field_doc.empty()) io << "    // " << field_doc << "\n";
            io << "    repeated " << proto3_type_(*inner) << " "
               << field_name << " = " << tags[0] << options << ";\n";
            return;
        }

        // std::optional<T> → optional T
        if (auto inner = std_optional_inner_(qt); inner) {
            const auto tags = read_field_int_args_(fld, "pb::field");
            if (tags.size() != 1) return;
            if (!field_doc.empty()) io << "    // " << field_doc << "\n";
            io << "    optional " << proto3_type_(*inner) << " "
               << field_name << " = " << tags[0] << options << ";\n";
            return;
        }

        // pb::adapter("Name") → google.protobuf.<Name> + tracked import
        const std::string adapter = read_field_string_attr_(fld, "pb::adapter");
        if (!adapter.empty()) {
            const auto tags = read_field_int_args_(fld, "pb::field");
            if (tags.size() != 1) return;
            if (!field_doc.empty()) io << "    // " << field_doc << "\n";
            if (adapter == "Timestamp") {
                track_import_("google/protobuf/timestamp.proto");
                io << "    google.protobuf.Timestamp ";
            } else if (adapter == "Duration") {
                track_import_("google/protobuf/duration.proto");
                io << "    google.protobuf.Duration ";
            } else {
                // Conservative guess at the import path. User can extend
                // this in a future tier-3 attribute (`pb::well_known_import`).
                std::string lower = adapter;
                for (char& c : lower) c = static_cast<char>(std::tolower(static_cast<unsigned char>(c)));
                track_import_("google/protobuf/" + lower + ".proto");
                io << "    google.protobuf." << adapter << " ";
            }
            io << field_name << " = " << tags[0] << options << ";\n";
            return;
        }

        // pb::wire override changes the proto3 type name (sint32, fixed64, …).
        const std::string wire_spec = read_field_string_attr_(fld, "pb::wire");

        // Scalar / enum / nested-message: pb::field(N)
        const auto tags = read_field_int_args_(fld, "pb::field");
        if (tags.size() != 1) return;
        if (!field_doc.empty()) io << "    // " << field_doc << "\n";
        io << "    "
           << (wire_spec.empty() ? proto3_type_(qt) : wire_spec)
           << " " << field_name << " = " << tags[0] << options << ";\n";
    }

    // ── oneof emission ──────────────────────────────────────────────────
    void emit_oneof_(const clang::FieldDecl* fld) {
        const auto tags = read_field_int_args_(fld, "pb::field");
        const std::string explicit_name = read_field_string_attr_(fld, "pb::oneof_name");
        const std::string group = explicit_name.empty() ? utils::name(fld) : explicit_name;

        // Extract non-monostate variant alternative types.
        const std::vector<std::string> alts = extract_variant_alt_types_(fld);
        if (alts.size() != tags.size()) return;     // mismatch handled by pb consumer

        io << "    oneof " << group << " {\n";
        for (std::size_t i = 0; i < alts.size(); ++i) {
            io << "        " << alts[i] << " " << group << "_" << (i+1)
               << " = " << tags[i] << ";\n";
        }
        io << "    }\n";
    }

    // ── Type mapping (C++ → proto3) ─────────────────────────────────────
    std::string proto3_type_(clang::QualType qt) const {
        qt = qt.getCanonicalType();
        const clang::Type* tp = qt.getTypePtrOrNull();
        if (!tp) return "/*unknown*/";

        if (tp->isBooleanType()) return "bool";
        if (tp->isFloatingType()) {
            if (tp->isSpecificBuiltinType(clang::BuiltinType::Float))  return "float";
            if (tp->isSpecificBuiltinType(clang::BuiltinType::Double)) return "double";
        }
        // Enum check BEFORE isIntegerType — scoped enums (`enum class`)
        // return false from isIntegerType(), so the previous nesting
        // missed them entirely and fell through to /*unsupported*/.
        if (tp->isEnumeralType()) {
            if (const auto* et = tp->getAs<clang::EnumType>()) {
                const clang::EnumDecl* ed = et->getDecl();
                // Reference the enum by its proto3 message-name mapping so
                // [[pb::name(...)]] on the enum decl propagates.
                const std::string explicit_name = read_enum_string_attr_(ed, "pb::name");
                return !explicit_name.empty()
                    ? explicit_name
                    : default_enum_name_(ed->getNameAsString());
            }
            return "int32";   // unlikely fallback
        }
        if (tp->isIntegerType()) {
            const auto bw = qt->getAs<clang::BuiltinType>();
            if (bw) {
                switch (bw->getKind()) {
                    case clang::BuiltinType::Int:      return "int32";
                    case clang::BuiltinType::Long:
                    case clang::BuiltinType::LongLong: return "int64";
                    case clang::BuiltinType::UInt:     return "uint32";
                    case clang::BuiltinType::ULong:
                    case clang::BuiltinType::ULongLong: return "uint64";
                    default: break;
                }
            }
        }
        if (is_std_string_(qt)) return "string";

        // Nested user message reference — use the canonicalized message name.
        if (tp->isRecordType()) {
            if (const auto* rec = tp->getAsCXXRecordDecl()) {
                if (!is_stdlib_record_(rec)) {
                    const std::string explicit_name = read_class_string_attr_(rec, "pb::name");
                    return !explicit_name.empty()
                        ? explicit_name
                        : default_message_name_(rec->getNameAsString());
                }
            }
        }

        return "/*unsupported*/";
    }

    bool is_std_string_(clang::QualType qt) const {
        const clang::Type* tp = qt.getTypePtrOrNull();
        if (!tp || !tp->isRecordType()) return false;
        const auto* spec =
            clang::dyn_cast<clang::ClassTemplateSpecializationDecl>(tp->getAsCXXRecordDecl());
        if (!spec) return false;
        return spec->getName() == "basic_string" && is_stdlib_record_(spec);
    }

    bool is_std_variant_(clang::QualType qt) const {
        const clang::Type* tp = qt.getTypePtrOrNull();
        if (!tp || !tp->isRecordType()) return false;
        const auto* spec =
            clang::dyn_cast<clang::ClassTemplateSpecializationDecl>(tp->getAsCXXRecordDecl());
        if (!spec) return false;
        return spec->getName() == "variant" && is_stdlib_record_(spec);
    }

    std::optional<clang::QualType> std_vector_inner_(clang::QualType qt) const {
        const clang::Type* tp = qt.getTypePtrOrNull();
        if (!tp || !tp->isRecordType()) return std::nullopt;
        const auto* spec =
            clang::dyn_cast<clang::ClassTemplateSpecializationDecl>(tp->getAsCXXRecordDecl());
        if (!spec || !is_stdlib_record_(spec)) return std::nullopt;
        if (spec->getName() != "vector") return std::nullopt;
        const auto& args = spec->getTemplateArgs();
        if (args.size() < 1 || args[0].getKind() != clang::TemplateArgument::Type)
            return std::nullopt;
        return args[0].getAsType();
    }

    std::optional<clang::QualType> std_optional_inner_(clang::QualType qt) const {
        const clang::Type* tp = qt.getTypePtrOrNull();
        if (!tp || !tp->isRecordType()) return std::nullopt;
        const auto* spec =
            clang::dyn_cast<clang::ClassTemplateSpecializationDecl>(tp->getAsCXXRecordDecl());
        if (!spec || !is_stdlib_record_(spec)) return std::nullopt;
        if (spec->getName() != "optional") return std::nullopt;
        const auto& args = spec->getTemplateArgs();
        if (args.size() < 1 || args[0].getKind() != clang::TemplateArgument::Type)
            return std::nullopt;
        return args[0].getAsType();
    }

    std::optional<std::pair<clang::QualType, clang::QualType>>
    std_map_kv_(clang::QualType qt) const {
        const clang::Type* tp = qt.getTypePtrOrNull();
        if (!tp || !tp->isRecordType()) return std::nullopt;
        const auto* spec =
            clang::dyn_cast<clang::ClassTemplateSpecializationDecl>(tp->getAsCXXRecordDecl());
        if (!spec || !is_stdlib_record_(spec)) return std::nullopt;
        const llvm::StringRef name = spec->getName();
        if (name != "map" && name != "unordered_map") return std::nullopt;
        const auto& args = spec->getTemplateArgs();
        if (args.size() < 2) return std::nullopt;
        if (args[0].getKind() != clang::TemplateArgument::Type ||
            args[1].getKind() != clang::TemplateArgument::Type) return std::nullopt;
        return std::make_pair(args[0].getAsType(), args[1].getAsType());
    }

    std::vector<std::string> extract_variant_alt_types_(const clang::FieldDecl* fld) const {
        std::vector<std::string> out;
        const clang::Type* tp = fld->getType().getTypePtrOrNull();
        if (!tp || !tp->isRecordType()) return out;
        const auto* spec =
            clang::dyn_cast<clang::ClassTemplateSpecializationDecl>(tp->getAsCXXRecordDecl());
        if (!spec) return out;
        for (const auto& arg : spec->getTemplateArgs().asArray()) {
            const auto handle = [&](clang::QualType qt) {
                const std::string s = proto3_type_(qt);
                if (s.find("monostate") != std::string::npos) return;
                if (s == "/*unsupported*/" || s == "/*unknown*/") return;
                out.push_back(s);
            };
            if (arg.getKind() == clang::TemplateArgument::Type) {
                handle(arg.getAsType());
            } else if (arg.getKind() == clang::TemplateArgument::Pack) {
                for (const auto& packed : arg.getPackAsArray()) {
                    if (packed.getKind() == clang::TemplateArgument::Type)
                        handle(packed.getAsType());
                }
            }
        }
        return out;
    }

    // ── Attribute readers (mirrors consumer_pb.hpp; deliberately
    //    Commit 3 refactor: all readers below delegate to
    //    pb_attr_reader::. Each future backend (JSON / SQL / Avro) reuses
    //    the same shared primitives — adding a new backend is "include
    //    pb_attr_reader.hpp + write the emit_*" work, with no
    //    AnnotateAttr-walking boilerplate to copy. ────────────────────────
    const clang::AnnotateAttr* find_annotate_(const clang::Decl* d,
                                                llvm::StringRef kind) const {
        return pb_attr_reader::find_annotate(d, kind);
    }
    bool has_attr_(const clang::Decl* d, llvm::StringRef kind) const {
        return pb_attr_reader::has_attr(d, kind);
    }
    std::string read_string_arg_(const clang::AnnotateAttr* ann) const {
        return pb_attr_reader::read_string_arg(ann);
    }
    std::string read_field_string_attr_(const clang::FieldDecl* fld, llvm::StringRef kind) const {
        return pb_attr_reader::read_field_string(fld, kind);
    }
    std::string read_class_string_attr_(const clang::CXXRecordDecl* rec, llvm::StringRef kind) const {
        return pb_attr_reader::read_class_string(rec, kind);
    }
    std::vector<std::uint32_t>
    read_field_int_args_(const clang::FieldDecl* fld, llvm::StringRef kind) const {
        return pb_attr_reader::read_field_ints(fld, kind);
    }
    std::vector<std::uint32_t>
    read_class_int_args_(const clang::CXXRecordDecl* rec, llvm::StringRef kind) const {
        return pb_attr_reader::read_class_ints(rec, kind);
    }
    std::vector<std::string>
    read_class_string_args_(const clang::CXXRecordDecl* rec, llvm::StringRef kind) const {
        return pb_attr_reader::read_class_strings(rec, kind);
    }
    std::optional<std::uint32_t>
    read_class_int_arg_(const clang::CXXRecordDecl* rec, llvm::StringRef kind) const {
        return pb_attr_reader::read_class_int(rec, kind);
    }

    // ── Naming ──────────────────────────────────────────────────────────
    std::string field_proto_name_(const clang::FieldDecl* fld) const {
        const std::string explicit_name = read_field_string_attr_(fld, "pb::name");
        const std::string base = !explicit_name.empty() ? explicit_name : utils::name(fld);
        return apply_name_convention_(base);
    }

    // Phase 4: pb::name_all — class-level naming convention applied to
    // each field name (subject to per-field [[pb::name(...)]] override).
    std::string apply_name_convention_(const std::string& s) const {
        if (current_name_convention.empty()) return s;
        if (current_name_convention == "snake_case") {
            std::string out;
            for (std::size_t i = 0; i < s.size(); ++i) {
                const char c = s[i];
                if (std::isupper(static_cast<unsigned char>(c)) && i != 0
                    && !std::isupper(static_cast<unsigned char>(s[i-1]))) {
                    out.push_back('_');
                }
                out.push_back(static_cast<char>(std::tolower(static_cast<unsigned char>(c))));
            }
            return out;
        }
        if (current_name_convention == "camelCase" ||
            current_name_convention == "PascalCase") {
            std::string out;
            const bool pascal = (current_name_convention == "PascalCase");
            bool cap = pascal;
            for (char c : s) {
                if (c == '_') { cap = true; continue; }
                out.push_back(cap ? static_cast<char>(std::toupper(static_cast<unsigned char>(c)))
                                  : c);
                cap = false;
            }
            return out;
        }
        return s;
    }

    // C++ struct identifier → proto3 message name.
    // Strip trailing _t / _type / _struct, then PascalCase.
    std::string default_message_name_(const std::string& cpp_name) const {
        std::string s = cpp_name;
        for (const char* suffix : { "_struct", "_type", "_t" }) {
            const std::size_t n = std::strlen(suffix);
            if (s.size() > n && s.compare(s.size() - n, n, suffix) == 0) {
                s.resize(s.size() - n);
                break;
            }
        }
        // snake_case → PascalCase
        std::string out;
        bool cap = true;
        for (char c : s) {
            if (c == '_') { cap = true; continue; }
            out.push_back(cap ? static_cast<char>(std::toupper(static_cast<unsigned char>(c)))
                              : c);
            cap = false;
        }
        return out;
    }
};
