/* Copyright (c) 2018-2026 Steven Varga, steven@vargalabs.com Toronto, ON Canada */

#pragma once

#include <fstream>
#include <sstream>
#include <map>
#include <set>
#include <string>
#include <vector>

#include <clang/AST/Decl.h>
#include <clang/AST/DeclCXX.h>
#include <clang/AST/Type.h>
#include <clang/ASTMatchers/ASTMatchFinder.h>

#include "utils.hpp"
#include "h5_attr_reader.hpp"

// Issue #37 — Avro descriptor backend emitter.
//
// Walks the same AST as the HDF5 and JSON backends, but emits a self-contained
// C++ header with constexpr type descriptors for the avro::meta runtime.
//
// All AST-dependent work happens inside run() while the AST is still alive.
// The destructor only formats and writes the accumulated C++ fragments.

class AvroTemplateCallback : public clang::ast_matchers::MatchFinder::MatchCallback {
public:
	explicit AvroTemplateCallback(const std::string& output_path)
		: output_path_(output_path) {}

	~AvroTemplateCallback() {
		std::ofstream io(output_path_);
		if (!io) return;

		io << "#pragma once\n\n";
		io << "/* Generated by h5cpp-compiler Avro backend */\n\n";
		io << "#include <cstddef>\n";
		io << "#include <cstdint>\n\n";

		io << "namespace avro::meta {\n\n";

		// ── base types ──
		io << "enum class avro_type_t : std::uint8_t {\n";
		io << "    null, boolean, int32, int64, float32, float64,\n";
		io << "    bytes, string, array, map, object, optional, fixed,\n";
		io << "    date, time_millis, time_micros,\n";
		io << "    timestamp_millis, timestamp_micros,\n";
		io << "    local_timestamp_millis, local_timestamp_micros,\n";
		io << "    decimal, uuid\n";
		io << "};\n\n";

		io << "struct field_desc {\n";
		io << "    const char*   json_name;\n";
		io << "    avro_type_t   type;\n";
		io << "    std::size_t   offset;\n";
		io << "    bool          required;\n";
		io << "    const char*   doc;\n";
		io << "    const field_desc* item;\n";
		io << "    const field_desc* key;\n";
		io << "    const field_desc* value;\n";
		io << "    const char*   fixed_name;\n";
		io << "    std::size_t   fixed_size;\n";
		io << "    std::uint8_t  decimal_precision;\n";
		io << "    std::uint8_t  decimal_scale;\n";
		io << "};\n\n";

		io << "template<typename T>\n";
		io << "struct descriptor {\n";
		io << "    static constexpr char alias[] = \"\";\n";
		io << "    static constexpr field_desc fields[] = {};\n";
		io << "    static constexpr std::size_t field_count = 0;\n";
		io << "};\n\n";

		io << "} // namespace avro::meta\n\n";

		for (const auto& name : order_) {
			auto it = descriptors_.find(name);
			if (it != descriptors_.end()) {
				io << it->second;
			}
		}
	}

	void run(const clang::ast_matchers::MatchFinder::MatchResult& Result) override {
		const clang::CXXRecordDecl* node = Result.Nodes.getNodeAs<clang::CXXRecordDecl>("cxxRecordDecl");
		if (!node) node = Result.Nodes.getNodeAs<clang::CXXRecordDecl>("classDecl");
		if (!node) return;

		if (!all_records_.insert(node).second) return;

		// Compute descriptors for this node and all dependencies while AST is alive.
		std::vector<const clang::CXXRecordDecl*> sorted;
		std::set<const clang::CXXRecordDecl*> visited;
		toposort_(node, visited, sorted);

		for (auto* rec : sorted) {
			std::string name = cpp_type_name_(rec);
			if (descriptors_.count(name)) continue;
			std::ostringstream oss;
			emit_descriptor_(oss, rec);
			descriptors_[name] = oss.str();
			order_.push_back(name);
		}
	}

private:
	std::string output_path_;
	std::set<const clang::CXXRecordDecl*> all_records_;
	std::map<std::string, std::string> descriptors_;
	std::vector<std::string> order_;
	std::set<const clang::CXXRecordDecl*> emitted_;
	mutable int item_counter_ = 0;

	// ── topological sort ──
	void toposort_(const clang::CXXRecordDecl* node,
	               std::set<const clang::CXXRecordDecl*>& visited,
	               std::vector<const clang::CXXRecordDecl*>& order) {
		if (!node || !visited.insert(node).second) return;
		for (clang::FieldDecl* fld : node->fields()) {
			clang::QualType qt = fld->getType();
			const clang::Type* tp = qt.getTypePtrOrNull();
			if (!tp) continue;

			// nested record (direct field)
			if (tp->isRecordType() && !utils::is_vector_type(qt)
			    && !utils::is_string_type(qt) && !is_map_type_(qt)
			    && !is_optional_type_(qt) && !is_chrono_time_point_(qt)
			    && !is_std_array_type_(qt)) {
				if (auto* rec = tp->getAsCXXRecordDecl()) {
					if (rec->getDefinition()) toposort_(rec->getDefinition(), visited, order);
				}
			}

			// array element type
			if (tp->isConstantArrayType()) {
				clang::QualType et = qt->getAsArrayTypeUnsafe()->getElementType();
				const clang::Type* etp = et.getTypePtrOrNull();
				if (etp && etp->isRecordType() && !utils::is_string_type(et) && !utils::is_vector_type(et) && !is_chrono_time_point_(et) && !is_std_array_type_(et)) {
					if (auto* rec = etp->getAsCXXRecordDecl()) {
						if (rec->getDefinition()) toposort_(rec->getDefinition(), visited, order);
					}
				}
			}

			// vector element type
			if (utils::is_vector_type(qt)) {
				clang::QualType et = utils::get_vector_element_type(qt);
				const clang::Type* etp = et.getTypePtrOrNull();
				if (etp && etp->isRecordType() && !utils::is_string_type(et) && !utils::is_vector_type(et) && !is_chrono_time_point_(et) && !is_std_array_type_(et)) {
					if (auto* rec = etp->getAsCXXRecordDecl()) {
						if (rec->getDefinition()) toposort_(rec->getDefinition(), visited, order);
					}
				}
			}

			// map value type
			if (is_map_type_(qt)) {
				clang::QualType vt = get_map_value_type_(qt);
				const clang::Type* vtp = vt.getTypePtrOrNull();
				if (vtp && vtp->isRecordType() && !utils::is_string_type(vt) && !utils::is_vector_type(vt) && !is_map_type_(vt) && !is_optional_type_(vt) && !is_chrono_time_point_(vt) && !is_std_array_type_(vt)) {
					if (auto* rec = vtp->getAsCXXRecordDecl()) {
						if (rec->getDefinition()) toposort_(rec->getDefinition(), visited, order);
					}
				}
			}

			// optional inner type
			if (is_optional_type_(qt)) {
				clang::QualType it = get_optional_inner_type_(qt);
				const clang::Type* itp = it.getTypePtrOrNull();
				if (itp && itp->isRecordType() && !utils::is_string_type(it) && !utils::is_vector_type(it) && !is_map_type_(it) && !is_optional_type_(it)) {
					if (auto* rec = itp->getAsCXXRecordDecl()) {
						if (rec->getDefinition()) toposort_(rec->getDefinition(), visited, order);
					}
				}
			}
		}
		order.push_back(node);
	}

	// ── AST type detection helpers ──
	static bool is_map_type_(const clang::QualType& qt) {
		const clang::Type* tp = qt.getTypePtrOrNull();
		if (!tp) return false;
		if (const auto* tst = tp->getAs<clang::TemplateSpecializationType>()) {
			if (const auto* td = tst->getTemplateName().getAsTemplateDecl()) {
				std::string name = td->getNameAsString();
				return name == "map" || name == "unordered_map";
			}
		}
		return false;
	}

	static bool is_optional_type_(const clang::QualType& qt) {
		const clang::Type* tp = qt.getTypePtrOrNull();
		if (!tp) return false;
		if (const auto* tst = tp->getAs<clang::TemplateSpecializationType>()) {
			if (const auto* td = tst->getTemplateName().getAsTemplateDecl()) {
				return td->getNameAsString() == "optional";
			}
		}
		return false;
	}

	static bool is_std_array_type_(const clang::QualType& qt) {
		const clang::Type* tp = qt.getTypePtrOrNull();
		if (!tp) return false;
		if (const auto* tst = tp->getAs<clang::TemplateSpecializationType>()) {
			if (const auto* td = tst->getTemplateName().getAsTemplateDecl()) {
				return td->getNameAsString() == "array";
			}
		}
		return false;
	}

	static clang::QualType get_map_key_type_(const clang::QualType& qt) {
		const clang::Type* tp = qt.getTypePtrOrNull();
		if (!tp) return clang::QualType();
		if (const auto* tst = tp->getAs<clang::TemplateSpecializationType>()) {
			auto args = tst->template_arguments();
			if (args.size() >= 1 && args[0].getKind() == clang::TemplateArgument::Type)
				return args[0].getAsType();
		}
		return clang::QualType();
	}

	static clang::QualType get_map_value_type_(const clang::QualType& qt) {
		const clang::Type* tp = qt.getTypePtrOrNull();
		if (!tp) return clang::QualType();
		if (const auto* tst = tp->getAs<clang::TemplateSpecializationType>()) {
			auto args = tst->template_arguments();
			if (args.size() >= 2 && args[1].getKind() == clang::TemplateArgument::Type)
				return args[1].getAsType();
		}
		return clang::QualType();
	}

	static clang::QualType get_optional_inner_type_(const clang::QualType& qt) {
		const clang::Type* tp = qt.getTypePtrOrNull();
		if (!tp) return clang::QualType();
		if (const auto* tst = tp->getAs<clang::TemplateSpecializationType>()) {
			auto args = tst->template_arguments();
			if (!args.empty() && args[0].getKind() == clang::TemplateArgument::Type)
				return args[0].getAsType();
		}
		return clang::QualType();
	}

	static clang::QualType get_array_element_type_(const clang::QualType& qt) {
		const clang::Type* tp = qt.getTypePtrOrNull();
		if (const auto* tst = tp->getAs<clang::TemplateSpecializationType>()) {
			auto args = tst->template_arguments();
			if (!args.empty() && args[0].getKind() == clang::TemplateArgument::Type)
				return args[0].getAsType();
		}
		return clang::QualType();
	}

	static std::size_t get_array_size_(const clang::QualType& qt) {
		const clang::Type* tp = qt.getTypePtrOrNull();
		if (const auto* tst = tp->getAs<clang::TemplateSpecializationType>()) {
			auto args = tst->template_arguments();
			if (args.size() >= 2 && args[1].getKind() == clang::TemplateArgument::Integral)
				return args[1].getAsIntegral().getLimitedValue();
		}
		// Fallback: read from the class template specialization decl
		if (const auto* rec = tp->getAsCXXRecordDecl()) {
			if (const auto* ctsd = llvm::dyn_cast<clang::ClassTemplateSpecializationDecl>(rec)) {
				const auto& args = ctsd->getTemplateArgs();
				if (args.size() >= 2 && args[1].getKind() == clang::TemplateArgument::Integral)
					return args[1].getAsIntegral().getLimitedValue();
			}
		}
		return 0;
	}

	static bool is_bin_vector_type_(const clang::QualType& qt) {
		if (!utils::is_vector_type(qt)) return false;
		clang::QualType et = utils::get_vector_element_type(qt);
		const clang::Type* etp = et.getTypePtrOrNull();
		if (!etp) return false;
		if (!etp->isBuiltinType()) return false;
		clang::QualType ct = et->getCanonicalTypeInternal();
		std::string name = ct.getAsString();
		return name == "unsigned char" || name == "char" || name == "std::uint8_t" || name == "uint8_t";
	}

	static bool is_byte_array_type_(const clang::QualType& qt) {
		if (!is_std_array_type_(qt)) return false;
		clang::QualType et = get_array_element_type_(qt);
		const clang::Type* etp = et.getTypePtrOrNull();
		if (!etp) return false;
		if (!etp->isBuiltinType()) return false;
		clang::QualType ct = et->getCanonicalTypeInternal();
		std::string name = ct.getAsString();
		return name == "unsigned char" || name == "char" || name == "std::uint8_t" || name == "uint8_t";
	}

	static bool is_chrono_time_point_(const clang::QualType& qt) {
		std::string name = qt.getAsString();
		return name.find("std::chrono::time_point") == 0 || name.find("time_point<") != std::string::npos;
	}

	static bool is_chrono_record_(const clang::CXXRecordDecl* node) {
		// Walk up the namespace chain to detect std::chrono types.
		const clang::DeclContext* ctx = node->getDeclContext();
		while (ctx) {
			if (ctx->isNamespace()) {
				if (const auto* ns = clang::NamespaceDecl::castFromDeclContext(ctx)) {
					std::string name = ns->getQualifiedNameAsString();
					if (name == "std::chrono" || name == "chrono") return true;
				}
			}
			ctx = ctx->getParent();
		}
		std::string qname = node->getQualifiedNameAsString();
		if (qname.find("std::chrono::") == 0) return true;
		if (qname.find("chrono::") == 0) return true;
		// Fallback: check the type string
		if (node->getTypeForDecl()) {
			clang::QualType qt(node->getTypeForDecl(), 0);
			std::string name = qt.getAsString();
			if (name.find("std::chrono::") != std::string::npos) return true;
			if (name.find("time_point<") != std::string::npos) return true;
			if (name.find("duration<") != std::string::npos) return true;
		}
		return false;
	}

	// ── type name for emitted code ──
	static std::string cpp_type_name_(const clang::CXXRecordDecl* node) {
		return node->getQualifiedNameAsString();
	}

	// ── emit one descriptor specialization ──
	void emit_descriptor_(std::ostream& io, const clang::CXXRecordDecl* node) {
		if (!emitted_.insert(node).second) return;
		if (is_chrono_record_(node)) return;

		std::string type_name = cpp_type_name_(node);
		std::string alias = h5_attr_reader::read_class_string(node, "avro::alias");

		io << "// descriptor for " << type_name << "\n";
		io << "template<>\n";
		io << "struct descriptor<" << type_name << "> {\n";

		if (!alias.empty()) {
			io << "    static constexpr char alias[] = \"" << alias << "\";\n";
		}

		// Emit any nested item descriptors first
		std::vector<std::string> nested_items;
		std::vector<std::string> field_inits;
		int local_counter = 0;

		for (clang::FieldDecl* fld : node->fields()) {
			if (h5_attr_reader::has_attr(fld, "avro::ignore")) continue;

			std::string wire_name = h5_attr_reader::read_field_string(fld, "avro::name");
			if (wire_name.empty()) wire_name = utils::name(fld);

			clang::QualType qt = fld->getType();
			bool required = h5_attr_reader::has_attr(fld, "avro::required");
			std::string doc = h5_attr_reader::read_field_string(fld, "avro::doc");

			std::string item_ref = "nullptr";
			std::string key_ref = "nullptr";
			std::string value_ref = "nullptr";
			std::string fixed_name = "nullptr";
			std::size_t fixed_size = 0;
			std::uint8_t decimal_precision = 0;
			std::uint8_t decimal_scale = 0;

			// Check Avro-specific field-level attributes first
			std::string type_str;
			if (h5_attr_reader::has_attr(fld, "avro::datetime")) {
				type_str = "avro_type_t::timestamp_millis";
			} else if (h5_attr_reader::has_attr(fld, "avro::timestamp")) {
				type_str = "avro_type_t::timestamp_micros";
			} else if (h5_attr_reader::has_attr(fld, "avro::uuid")) {
				type_str = "avro_type_t::uuid";
			} else if (h5_attr_reader::has_attr(fld, "avro::date")) {
				type_str = "avro_type_t::date";
			} else if (h5_attr_reader::has_attr(fld, "avro::time")) {
				type_str = "avro_type_t::time_millis";
			} else {
				auto dec_opt = h5_attr_reader::read_field_ints(fld, "avro::decimal");
				if (!dec_opt.empty()) {
					type_str = "avro_type_t::decimal";
					decimal_precision = static_cast<std::uint8_t>(dec_opt[0]);
					if (dec_opt.size() >= 2) {
						decimal_scale = static_cast<std::uint8_t>(dec_opt[1]);
					}
				} else {
					std::string fixed_attr_name = h5_attr_reader::read_field_string(fld, "avro::fixed");
					if (!fixed_attr_name.empty() && is_byte_array_type_(qt)) {
						type_str = "avro_type_t::fixed";
						fixed_name = "\"" + fixed_attr_name + "\"";
						auto fixed_ints = h5_attr_reader::read_field_ints(fld, "avro::fixed");
						if (!fixed_ints.empty()) {
							fixed_size = static_cast<std::size_t>(fixed_ints[0]);
						} else {
							fixed_size = get_array_size_(qt);
						}
					} else {
						type_str = avro_type_str_(qt, nested_items, item_ref, key_ref, value_ref, local_counter);
					}
				}
			}

			// Optional fields are never required (Avro union [null, T])
			if (is_optional_type_(qt)) {
				required = false;
			}

			std::ostringstream init;
			init << "        { \"" << wire_name << "\", " << type_str;
			init << ", offsetof(" << type_name << ", " << utils::name(fld) << "), ";
			init << (required ? "true" : "false") << ", ";
			if (doc.empty()) init << "nullptr";
			else init << "\"" << doc << "\"";
			init << ", " << item_ref << ", " << key_ref << ", " << value_ref;
			init << ", " << fixed_name << ", " << fixed_size;
			init << ", " << static_cast<int>(decimal_precision) << ", " << static_cast<int>(decimal_scale) << " }";
			field_inits.push_back(init.str());
		}

		// Write nested item descriptors
		for (const auto& ni : nested_items) {
			io << "    " << ni << "\n";
		}

		io << "    static constexpr field_desc fields[] = {\n";
		for (std::size_t i = 0; i < field_inits.size(); ++i) {
			if (i > 0) io << ",\n";
			io << field_inits[i];
		}
		io << "\n    };\n";
		io << "    static constexpr std::size_t field_count = " << field_inits.size() << ";\n";
		io << "};\n\n";
	}

	// ── C++ type → Avro type string ──
	std::string avro_type_str_(clang::QualType qt,
	                         std::vector<std::string>& nested_items,
	                         std::string& item_ref,
	                         std::string& key_ref,
	                         std::string& value_ref,
	                         int& local_counter) const {
		const clang::Type* tp = qt.getTypePtrOrNull();
		if (!tp) return "avro_type_t::null";

		// primitive / builtin
		if (tp->isBuiltinType()) {
			clang::QualType ct = qt->getCanonicalTypeInternal();
			std::string name = ct.getAsString();
			if (name == "bool" || name == "_Bool") return "avro_type_t::boolean";
			if (name == "char") return "avro_type_t::int32";
			if (name == "signed char") return "avro_type_t::int32";
			if (name == "unsigned char") return "avro_type_t::int32";
			if (name == "short") return "avro_type_t::int32";
			if (name == "unsigned short") return "avro_type_t::int32";
			if (name == "int") return "avro_type_t::int32";
			if (name == "unsigned int") return "avro_type_t::int64";
			if (name == "long") return "avro_type_t::int64";
			if (name == "unsigned long") return "avro_type_t::int64";
			if (name == "long long") return "avro_type_t::int64";
			if (name == "unsigned long long") return "avro_type_t::int64";
			if (name == "float") return "avro_type_t::float32";
			if (name == "double" || name == "long double") return "avro_type_t::float64";
			return "avro_type_t::null";
		}

		if (tp->isEnumeralType()) {
			return "avro_type_t::int32"; // Avro has enum type, but emit as int32 for now
		}

		if (utils::is_string_type(qt)) {
			return "avro_type_t::string";
		}

		if (is_bin_vector_type_(qt)) {
			return "avro_type_t::bytes";
		}

		if (is_byte_array_type_(qt)) {
			return "avro_type_t::bytes";
		}

		if (utils::is_vector_type(qt)) {
			clang::QualType et = utils::get_vector_element_type(qt);
			std::string sub_item = "nullptr";
			std::string sub_key = "nullptr";
			std::string sub_value = "nullptr";
			std::string elem_type = avro_type_str_(et, nested_items, sub_item, sub_key, sub_value, local_counter);
			int id = ++local_counter;
			std::string var_name = "item_" + std::to_string(id);
			std::ostringstream item_def;
			item_def << "static constexpr field_desc " << var_name
			         << " { nullptr, " << elem_type << ", 0, false, nullptr, "
			         << sub_item << ", " << sub_key << ", " << sub_value
			         << ", nullptr, 0, 0, 0 };";
			nested_items.push_back(item_def.str());
			item_ref = "&" + var_name;
			return "avro_type_t::array";
		}

		if (tp->isConstantArrayType()) {
			clang::QualType et = qt->getAsArrayTypeUnsafe()->getElementType();
			std::string sub_item = "nullptr";
			std::string sub_key = "nullptr";
			std::string sub_value = "nullptr";
			std::string elem_type = avro_type_str_(et, nested_items, sub_item, sub_key, sub_value, local_counter);
			int id = ++local_counter;
			std::string var_name = "item_" + std::to_string(id);
			std::ostringstream item_def;
			item_def << "static constexpr field_desc " << var_name
			         << " { nullptr, " << elem_type << ", 0, false, nullptr, "
			         << sub_item << ", " << sub_key << ", " << sub_value
			         << ", nullptr, 0, 0, 0 };";
			nested_items.push_back(item_def.str());
			item_ref = "&" + var_name;
			return "avro_type_t::array";
		}

		if (is_map_type_(qt)) {
			clang::QualType kt = get_map_key_type_(qt);
			clang::QualType vt = get_map_value_type_(qt);
			std::string k_item = "nullptr", k_key = "nullptr", k_value = "nullptr";
			std::string v_item = "nullptr", v_key = "nullptr", v_value = "nullptr";
			std::string key_type = avro_type_str_(kt, nested_items, k_item, k_key, k_value, local_counter);
			std::string val_type = avro_type_str_(vt, nested_items, v_item, v_key, v_value, local_counter);
			int id_k = ++local_counter;
			int id_v = ++local_counter;
			std::string var_k = "key_" + std::to_string(id_k);
			std::string var_v = "value_" + std::to_string(id_v);
			std::ostringstream key_def;
			key_def << "static constexpr field_desc " << var_k
			        << " { nullptr, " << key_type << ", 0, false, nullptr, "
			        << k_item << ", " << k_key << ", " << k_value
			        << ", nullptr, 0, 0, 0 };";
			nested_items.push_back(key_def.str());
			std::ostringstream val_def;
			val_def << "static constexpr field_desc " << var_v
			        << " { nullptr, " << val_type << ", 0, false, nullptr, "
			        << v_item << ", " << v_key << ", " << v_value
			        << ", nullptr, 0, 0, 0 };";
			nested_items.push_back(val_def.str());
			key_ref = "&" + var_k;
			value_ref = "&" + var_v;
			return "avro_type_t::map";
		}

		if (is_optional_type_(qt)) {
			clang::QualType it = get_optional_inner_type_(qt);
			std::string sub_item = "nullptr";
			std::string sub_key = "nullptr";
			std::string sub_value = "nullptr";
			std::string inner_type = avro_type_str_(it, nested_items, sub_item, sub_key, sub_value, local_counter);
			int id = ++local_counter;
			std::string var_name = "opt_" + std::to_string(id);
			std::ostringstream item_def;
			item_def << "static constexpr field_desc " << var_name
			         << " { nullptr, " << inner_type << ", 0, false, nullptr, "
			         << sub_item << ", " << sub_key << ", " << sub_value
			         << ", nullptr, 0, 0, 0 };";
			nested_items.push_back(item_def.str());
			item_ref = "&" + var_name;
			return "avro_type_t::optional";
		}

		if (is_chrono_time_point_(qt)) {
			return "avro_type_t::timestamp_millis";
		}

		if (tp->isRecordType()) {
			return "avro_type_t::object";
		}

		return "avro_type_t::null";
	}
};
