/* Copyright (c) 2018-2026 Steven Varga, steven@vargalabs.com Toronto, ON Canada */

#pragma once

#include <fstream>
#include <sstream>
#include <map>
#include <set>
#include <string>
#include <vector>

#include <clang/AST/Decl.h>
#include <clang/AST/DeclCXX.h>
#include <clang/AST/Type.h>
#include <clang/ASTMatchers/ASTMatchFinder.h>

#include "utils.hpp"
#include "h5_attr_reader.hpp"

// Issue #35 — CBOR descriptor backend emitter.
//
// Walks the same AST as the HDF5 and JSON backends, but emits a self-contained
// C++ header with constexpr type descriptors for the cbor::meta runtime.
//
// All AST-dependent work happens inside run() while the AST is still alive.
// The destructor only formats and writes the accumulated C++ fragments.

class CborTemplateCallback : public clang::ast_matchers::MatchFinder::MatchCallback {
public:
	explicit CborTemplateCallback(const std::string& output_path)
		: output_path_(output_path) {}

	~CborTemplateCallback() {
		std::ofstream io(output_path_);
		if (!io) return;

		io << "#pragma once\n\n";
		io << "/* Generated by h5cpp-compiler CBOR backend */\n\n";
		io << "#include <cstddef>\n";
		io << "#include <cstdint>\n\n";

		io << "namespace cbor::meta {\n\n";

		// ── base types ──
		io << "enum class cbor_type_t : std::uint8_t {\n";
		io << "    nil, boolean,\n";
		io << "    int8, int16, int32, int64,\n";
		io << "    uint8, uint16, uint32, uint64,\n";
		io << "    float16, float32, float64,\n";
		io << "    str, str_indef, bin, bin_indef, array, array_indef, map, map_indef, object, tag, optional\n";
		io << "};\n\n";

		io << "struct field_desc {\n";
		io << "    const char*   json_name;\n";
		io << "    cbor_type_t     type;\n";
		io << "    std::uint64_t tag_type;\n";
		io << "    std::size_t   offset;\n";
		io << "    bool          required;\n";
		io << "    const char*   doc;\n";
		io << "    const field_desc* item;\n";
		io << "    const field_desc* key;\n";
		io << "    const field_desc* value;\n";
		io << "};\n\n";

		io << "template<typename T>\n";
		io << "struct descriptor {\n";
		io << "    static constexpr char alias[] = \"\";\n";
		io << "    static constexpr std::uint64_t tag_id = 0;\n";
		io << "    static constexpr field_desc fields[] = {};\n";
		io << "    static constexpr std::size_t field_count = 0;\n";
		io << "};\n\n";

		io << "} // namespace cbor::meta\n\n";

		for (const auto& name : order_) {
			auto it = descriptors_.find(name);
			if (it != descriptors_.end()) {
				io << it->second;
			}
		}
	}

	void run(const clang::ast_matchers::MatchFinder::MatchResult& Result) override {
		const clang::CXXRecordDecl* node = Result.Nodes.getNodeAs<clang::CXXRecordDecl>("cxxRecordDecl");
		if (!node) node = Result.Nodes.getNodeAs<clang::CXXRecordDecl>("classDecl");
		if (!node) return;

		if (!all_records_.insert(node).second) return;

		// Compute descriptors for this node and all dependencies while AST is alive.
		std::vector<const clang::CXXRecordDecl*> sorted;
		std::set<const clang::CXXRecordDecl*> visited;
		toposort_(node, visited, sorted);

		for (auto* rec : sorted) {
			std::string name = cpp_type_name_(rec);
			if (descriptors_.count(name)) continue;
			std::ostringstream oss;
			emit_descriptor_(oss, rec);
			descriptors_[name] = oss.str();
			order_.push_back(name);
		}
	}

private:
	std::string output_path_;
	std::set<const clang::CXXRecordDecl*> all_records_;
	std::map<std::string, std::string> descriptors_;
	std::vector<std::string> order_;
	std::set<const clang::CXXRecordDecl*> emitted_;
	mutable int item_counter_ = 0;

	// ── topological sort ──
	void toposort_(const clang::CXXRecordDecl* node,
	               std::set<const clang::CXXRecordDecl*>& visited,
	               std::vector<const clang::CXXRecordDecl*>& order) {
		if (!node || !visited.insert(node).second) return;
		for (clang::FieldDecl* fld : node->fields()) {
			clang::QualType qt = fld->getType();
			const clang::Type* tp = qt.getTypePtrOrNull();
			if (!tp) continue;

			// nested record (direct field)
			if (tp->isRecordType() && !utils::is_vector_type(qt)
			    && !utils::is_string_type(qt) && !is_map_type_(qt)
			    && !is_optional_type_(qt)) {
				if (auto* rec = tp->getAsCXXRecordDecl()) {
					if (rec->getDefinition()) toposort_(rec->getDefinition(), visited, order);
				}
			}

			// array element type
			if (tp->isConstantArrayType()) {
				clang::QualType et = qt->getAsArrayTypeUnsafe()->getElementType();
				const clang::Type* etp = et.getTypePtrOrNull();
				if (etp && etp->isRecordType() && !utils::is_string_type(et) && !utils::is_vector_type(et)) {
					if (auto* rec = etp->getAsCXXRecordDecl()) {
						if (rec->getDefinition()) toposort_(rec->getDefinition(), visited, order);
					}
				}
			}

			// vector element type
			if (utils::is_vector_type(qt)) {
				clang::QualType et = utils::get_vector_element_type(qt);
				const clang::Type* etp = et.getTypePtrOrNull();
				if (etp && etp->isRecordType() && !utils::is_string_type(et) && !utils::is_vector_type(et)) {
					if (auto* rec = etp->getAsCXXRecordDecl()) {
						if (rec->getDefinition()) toposort_(rec->getDefinition(), visited, order);
					}
				}
			}

			// map value type
			if (is_map_type_(qt)) {
				clang::QualType vt = get_map_value_type_(qt);
				const clang::Type* vtp = vt.getTypePtrOrNull();
				if (vtp && vtp->isRecordType() && !utils::is_string_type(vt) && !utils::is_vector_type(vt) && !is_map_type_(vt) && !is_optional_type_(vt)) {
					if (auto* rec = vtp->getAsCXXRecordDecl()) {
						if (rec->getDefinition()) toposort_(rec->getDefinition(), visited, order);
					}
				}
			}

			// optional inner type
			if (is_optional_type_(qt)) {
				clang::QualType it = get_optional_inner_type_(qt);
				const clang::Type* itp = it.getTypePtrOrNull();
				if (itp && itp->isRecordType() && !utils::is_string_type(it) && !utils::is_vector_type(it) && !is_map_type_(it) && !is_optional_type_(it)) {
					if (auto* rec = itp->getAsCXXRecordDecl()) {
						if (rec->getDefinition()) toposort_(rec->getDefinition(), visited, order);
					}
				}
			}
		}
		order.push_back(node);
	}

	// ── AST type detection helpers ──
	static bool is_map_type_(const clang::QualType& qt) {
		const clang::Type* tp = qt.getTypePtrOrNull();
		if (!tp) return false;
		if (const auto* tst = tp->getAs<clang::TemplateSpecializationType>()) {
			if (const auto* td = tst->getTemplateName().getAsTemplateDecl()) {
				std::string name = td->getNameAsString();
				return name == "map" || name == "unordered_map";
			}
		}
		return false;
	}

	static bool is_optional_type_(const clang::QualType& qt) {
		const clang::Type* tp = qt.getTypePtrOrNull();
		if (!tp) return false;
		if (const auto* tst = tp->getAs<clang::TemplateSpecializationType>()) {
			if (const auto* td = tst->getTemplateName().getAsTemplateDecl()) {
				return td->getNameAsString() == "optional";
			}
		}
		return false;
	}

	static clang::QualType get_map_key_type_(const clang::QualType& qt) {
		const clang::Type* tp = qt.getTypePtrOrNull();
		if (!tp) return clang::QualType();
		if (const auto* tst = tp->getAs<clang::TemplateSpecializationType>()) {
			auto args = tst->template_arguments();
			if (args.size() >= 1 && args[0].getKind() == clang::TemplateArgument::Type)
				return args[0].getAsType();
		}
		return clang::QualType();
	}

	static clang::QualType get_map_value_type_(const clang::QualType& qt) {
		const clang::Type* tp = qt.getTypePtrOrNull();
		if (!tp) return clang::QualType();
		if (const auto* tst = tp->getAs<clang::TemplateSpecializationType>()) {
			auto args = tst->template_arguments();
			if (args.size() >= 2 && args[1].getKind() == clang::TemplateArgument::Type)
				return args[1].getAsType();
		}
		return clang::QualType();
	}

	static clang::QualType get_optional_inner_type_(const clang::QualType& qt) {
		const clang::Type* tp = qt.getTypePtrOrNull();
		if (!tp) return clang::QualType();
		if (const auto* tst = tp->getAs<clang::TemplateSpecializationType>()) {
			auto args = tst->template_arguments();
			if (!args.empty() && args[0].getKind() == clang::TemplateArgument::Type)
				return args[0].getAsType();
		}
		return clang::QualType();
	}

	static bool is_bin_vector_type_(const clang::QualType& qt) {
		if (!utils::is_vector_type(qt)) return false;
		clang::QualType et = utils::get_vector_element_type(qt);
		const clang::Type* etp = et.getTypePtrOrNull();
		if (!etp) return false;
		if (!etp->isBuiltinType()) return false;
		clang::QualType ct = et->getCanonicalTypeInternal();
		std::string name = ct.getAsString();
		return name == "unsigned char" || name == "char" || name == "std::uint8_t" || name == "uint8_t";
	}

	// ── type name for emitted code ──
	static std::string cpp_type_name_(const clang::CXXRecordDecl* node) {
		return node->getQualifiedNameAsString();
	}

	// ── emit one descriptor specialization ──
	void emit_descriptor_(std::ostream& io, const clang::CXXRecordDecl* node) {
		if (!emitted_.insert(node).second) return;

		std::string type_name = cpp_type_name_(node);
		std::string alias = h5_attr_reader::read_class_string(node, "cbor::alias");
		auto ext_opt = h5_attr_reader::read_class_int(node, "cbor::tag");

		io << "// descriptor for " << type_name << "\n";
		io << "template<>\n";
		io << "struct descriptor<" << type_name << "> {\n";

		if (!alias.empty()) {
			io << "    static constexpr char alias[] = \"" << alias << "\";\n";
		}
		if (ext_opt.has_value()) {
			io << "    static constexpr std::uint64_t tag_id = " << ext_opt.value() << "ull;\n";
		}

		// Emit any nested item descriptors first
		std::vector<std::string> nested_items;
		std::vector<std::string> field_inits;
		int local_counter = 0;

		for (clang::FieldDecl* fld : node->fields()) {
			if (h5_attr_reader::has_attr(fld, "cbor::ignore")) continue;

			std::string wire_name = h5_attr_reader::read_field_string(fld, "cbor::name");
			if (wire_name.empty()) wire_name = utils::name(fld);

			clang::QualType qt = fld->getType();
			bool required = h5_attr_reader::has_attr(fld, "cbor::required");
			std::string doc = h5_attr_reader::read_field_string(fld, "cbor::doc");

			std::string item_ref = "nullptr";
			std::string key_ref = "nullptr";
			std::string value_ref = "nullptr";
			std::string type_str = mp_type_str_(qt, nested_items, item_ref, key_ref, value_ref, local_counter);
			std::uint64_t tag_type = 0;

			// If the field type is a record with [[cbor::tag]], reference its tag_id
			const clang::Type* tp = qt.getTypePtrOrNull();
			if (tp && tp->isRecordType() && !utils::is_vector_type(qt)
			    && !utils::is_string_type(qt) && !is_map_type_(qt)
			    && !is_optional_type_(qt)) {
				if (auto* rec = tp->getAsCXXRecordDecl()) {
					if (rec->getDefinition()) {
						auto ftag = h5_attr_reader::read_class_int(rec->getDefinition(), "cbor::tag");
						if (ftag.has_value()) {
							type_str = "cbor_type_t::tag";
							tag_type = static_cast<std::uint64_t>(ftag.value());
						}
					}
				}
			}

			std::ostringstream init;
			init << "        { \"" << wire_name << "\", " << type_str << ", " << tag_type << "ull";
			init << ", offsetof(" << type_name << ", " << utils::name(fld) << "), ";
			init << (required ? "true" : "false") << ", ";
			if (doc.empty()) init << "nullptr";
			else init << "\"" << doc << "\"";
			init << ", " << item_ref << ", " << key_ref << ", " << value_ref << " }";
			field_inits.push_back(init.str());
		}

		// Write nested item descriptors
		for (const auto& ni : nested_items) {
			io << "    " << ni << "\n";
		}

		io << "    static constexpr field_desc fields[] = {\n";
		for (std::size_t i = 0; i < field_inits.size(); ++i) {
			if (i > 0) io << ",\n";
			io << field_inits[i];
		}
		io << "\n    };\n";
		io << "    static constexpr std::size_t field_count = " << field_inits.size() << ";\n";
		io << "};\n\n";
	}

	// ── C++ type → CBOR type string ──
	std::string mp_type_str_(clang::QualType qt,
	                         std::vector<std::string>& nested_items,
	                         std::string& item_ref,
	                         std::string& key_ref,
	                         std::string& value_ref,
	                         int& local_counter) const {
		const clang::Type* tp = qt.getTypePtrOrNull();
		if (!tp) return "cbor_type_t::nil";

		// primitive / builtin
		if (tp->isBuiltinType()) {
			clang::QualType ct = qt->getCanonicalTypeInternal();
			std::string name = ct.getAsString();
			if (name == "bool" || name == "_Bool") return "cbor_type_t::boolean";
			if (name == "char") return "cbor_type_t::int8";
			if (name == "signed char") return "cbor_type_t::int8";
			if (name == "unsigned char") return "cbor_type_t::uint8";
			if (name == "short") return "cbor_type_t::int16";
			if (name == "unsigned short") return "cbor_type_t::uint16";
			if (name == "int") return "cbor_type_t::int32";
			if (name == "unsigned int") return "cbor_type_t::uint32";
			if (name == "long") return "cbor_type_t::int64";
			if (name == "unsigned long") return "cbor_type_t::uint64";
			if (name == "long long") return "cbor_type_t::int64";
			if (name == "unsigned long long") return "cbor_type_t::uint64";
			if (name == "float") return "cbor_type_t::float32";
			if (name == "double" || name == "long double") return "cbor_type_t::float64";
			return "cbor_type_t::nil";
		}

		if (tp->isEnumeralType()) {
			return "cbor_type_t::int32"; // CBOR has no enum type; use underlying int
		}

		if (utils::is_string_type(qt)) {
			return "cbor_type_t::str";
		}

		if (is_bin_vector_type_(qt)) {
			return "cbor_type_t::bin";
		}

		if (utils::is_vector_type(qt)) {
			clang::QualType et = utils::get_vector_element_type(qt);
			std::string sub_item = "nullptr";
			std::string sub_key = "nullptr";
			std::string sub_value = "nullptr";
			std::string elem_type = mp_type_str_(et, nested_items, sub_item, sub_key, sub_value, local_counter);
			int id = ++local_counter;
			std::string var_name = "item_" + std::to_string(id);
			std::ostringstream item_def;
			item_def << "static constexpr field_desc " << var_name
			         << " { nullptr, " << elem_type << ", 0, 0, false, nullptr, "
			         << sub_item << ", " << sub_key << ", " << sub_value << " };";
			nested_items.push_back(item_def.str());
			item_ref = "&" + var_name;
			return "cbor_type_t::array";
		}

		if (tp->isConstantArrayType()) {
			clang::QualType et = qt->getAsArrayTypeUnsafe()->getElementType();
			std::string sub_item = "nullptr";
			std::string sub_key = "nullptr";
			std::string sub_value = "nullptr";
			std::string elem_type = mp_type_str_(et, nested_items, sub_item, sub_key, sub_value, local_counter);
			int id = ++local_counter;
			std::string var_name = "item_" + std::to_string(id);
			std::ostringstream item_def;
			item_def << "static constexpr field_desc " << var_name
			         << " { nullptr, " << elem_type << ", 0, 0, false, nullptr, "
			         << sub_item << ", " << sub_key << ", " << sub_value << " };";
			nested_items.push_back(item_def.str());
			item_ref = "&" + var_name;
			return "cbor_type_t::array";
		}

		if (is_map_type_(qt)) {
			clang::QualType kt = get_map_key_type_(qt);
			clang::QualType vt = get_map_value_type_(qt);
			std::string k_item = "nullptr", k_key = "nullptr", k_value = "nullptr";
			std::string v_item = "nullptr", v_key = "nullptr", v_value = "nullptr";
			std::string key_type = mp_type_str_(kt, nested_items, k_item, k_key, k_value, local_counter);
			std::string val_type = mp_type_str_(vt, nested_items, v_item, v_key, v_value, local_counter);
			int id_k = ++local_counter;
			int id_v = ++local_counter;
			std::string var_k = "key_" + std::to_string(id_k);
			std::string var_v = "value_" + std::to_string(id_v);
			std::ostringstream key_def;
			key_def << "static constexpr field_desc " << var_k
			        << " { nullptr, " << key_type << ", 0, 0, false, nullptr, "
			        << k_item << ", " << k_key << ", " << k_value << " };";
			nested_items.push_back(key_def.str());
			std::ostringstream val_def;
			val_def << "static constexpr field_desc " << var_v
			        << " { nullptr, " << val_type << ", 0, 0, false, nullptr, "
			        << v_item << ", " << v_key << ", " << v_value << " };";
			nested_items.push_back(val_def.str());
			key_ref = "&" + var_k;
			value_ref = "&" + var_v;
			return "cbor_type_t::map";
		}

		if (is_optional_type_(qt)) {
			clang::QualType it = get_optional_inner_type_(qt);
			std::string sub_item = "nullptr";
			std::string sub_key = "nullptr";
			std::string sub_value = "nullptr";
			std::string inner_type = mp_type_str_(it, nested_items, sub_item, sub_key, sub_value, local_counter);
			int id = ++local_counter;
			std::string var_name = "opt_" + std::to_string(id);
			std::ostringstream item_def;
			item_def << "static constexpr field_desc " << var_name
			         << " { nullptr, " << inner_type << ", 0, 0, false, nullptr, "
			         << sub_item << ", " << sub_key << ", " << sub_value << " };";
			nested_items.push_back(item_def.str());
			item_ref = "&" + var_name;
			return "cbor_type_t::optional";
		}

		if (tp->isRecordType()) {
			return "cbor_type_t::object";
		}

		return "cbor_type_t::nil";
	}
};
