/*
 * Copyright (c) 2018-2020 Steven Varga, Toronto,ON Canada
 * Author: Varga, Steven <steven@vargaconsulting.ca>
 */

#ifndef  H5CPP_PRODUCER_H5_HPP
#define  H5CPP_PRODUCER_H5_HPP

#include <iomanip>
#include <random>
#include <set>


std::string get_include_guard( size_t N ){
	std::string str;
	static const char alphabet[] = "abcdefghijklmnopqrstuvwxyz"
										"ABCDEFGHIJKLMNOPQRSTUVWXYZ";
	std::random_device rd;
	std::default_random_engine rng(rd());
	std::uniform_int_distribution<> dist(0,sizeof(alphabet)/sizeof(*alphabet)-2);

	std::generate_n(std::back_inserter(str), N, [&]() {
								return alphabet[dist(rng)];
							});
	return str;
}


struct H5Producer : Producer<H5Producer> {

	void file_begin_impl();
	void file_end_impl();
	void template_decl_impl(const std::string& name);
	void record_decl_impl(const std::string& var, const std::string& name);
	void return_type_impl(const std::string& type);
	void array_decl_impl(const std::string& var, const std::string& type, uint64_t size);
	void type_insert_impl(const std::string& var, const std::string& field_name,
	                      const std::string& record_name, const std::string& type);
	void type_release_impl();

	bool cache_add_impl(const std::string& key, const std::string& type);
	std::string cache_impl(const std::string& type);

	private:
	// type-lookup cache: maps Clang canonical type strings to C++ type strings
	std::map<std::string, std::string> cpp2hid;
	// maps array variable names ("at_XX") to their C++ array type string
	std::map<std::string, std::string> array_type_for_var;
	// tracks which record specializations have been emitted (dedup across runs)
	std::set<std::string> emitted_records;

	struct FieldInfo { std::string name; std::string cpp_type; };
	std::string          cur_rec_name;
	std::vector<FieldInfo> cur_rec_fields;
	bool                 has_pending_record = false;

	void emit_record_spec();
	static std::string make_array_type(const std::string& elem_type, uint64_t size);
};

// Build a C++ array type string by inserting a new outer dimension.
//   "float"             + 7 -> "float[7]"
//   "float[7]"          + 3 -> "float[3][7]"
//   "sn::other::Record" + 5 -> "sn::other::Record[5]"
std::string H5Producer::make_array_type(const std::string& elem_type, uint64_t size) {
	auto pos = elem_type.find('[');
	if (pos != std::string::npos)
		return elem_type.substr(0, pos) + "[" + std::to_string(size) + "]"
		       + elem_type.substr(pos);
	else
		return elem_type + "[" + std::to_string(size) + "]";
}

// Emit a compiler_meta_t<T> specialisation for cur_rec_name / cur_rec_fields.
// Skipped silently if the same record was already emitted in this file.
void H5Producer::emit_record_spec() {
	if (!has_pending_record) return;
	has_pending_record = false;

	if (emitted_records.count(cur_rec_name)) {
		cur_rec_fields.clear();
		return;
	}
	emitted_records.insert(cur_rec_name);

	const std::string& rn = cur_rec_name;

	io << "    template<> struct is_reflected_compound_t<" << rn
	   << "> : std::true_type {};\n";
	io << "    template<> struct compiler_meta_t<" << rn << "> {\n";
	io << "        static constexpr std::uint32_t version = 1;\n";

	for (size_t i = 0; i < cur_rec_fields.size(); ++i) {
		const auto& f = cur_rec_fields[i];
		io << "        struct f" << i << " { // " << f.name << "\n";
		io << "            using owner_type = " << rn << ";\n";
		io << "            using field_type = " << f.cpp_type << ";\n";
		io << "            static constexpr const char* name() noexcept"
		      " { return \"" << f.name << "\"; }\n";
		io << "            static constexpr std::size_t offset ="
		      " offsetof(" << rn << ", " << f.name << ");\n";
		io << "        };\n";
	}

	io << "        using fields_t = std::tuple<";
	for (size_t i = 0; i < cur_rec_fields.size(); ++i) {
		if (i) io << ", ";
		io << "f" << i;
	}
	io << ">;\n";
	io << "    };\n\n";

	cur_rec_fields.clear();
}

// ---------------------------------------------------------------------------
// File begin / end
// ---------------------------------------------------------------------------

void H5Producer::file_begin_impl() {
	io <<
		"/* Copyright (c) 2018 vargaconsulting, Toronto,ON Canada\n"
		" *     Author: Varga, Steven <steven@vargaconsulting.ca>\n"
		" * NOTE: generated by h5cpp compiler\n"
		" *       Requires h5cpp type engine v1 (issue #87).\n"
		" *       NOT compatible with h5cpp versions prior to the #87 merge.\n"
		" */\n";
	std::string include_guard = "H5CPP_GUARD_" + get_include_guard(5);

	io << "#ifndef " << include_guard << "\n";
	io << "#define " << include_guard << "\n\n";

	io << "#include <cstddef>\n";
	io << "#include <cstdint>\n";
	io << "#include <tuple>\n\n";

	io << "namespace h5::meta {\n\n";
	emitted_records.clear();
}

void H5Producer::file_end_impl() {
	io << "} // namespace h5::meta\n";
	io << "#endif\n";
}

// ---------------------------------------------------------------------------
// Per-struct production methods
// ---------------------------------------------------------------------------

void H5Producer::template_decl_impl(const std::string& /*record*/) {
	// Initialise the type-lookup cache with C++ canonical type names.
	// Clang uses "_Bool" for bool; map it to "bool" so storage_traits_t<bool>
	// dispatches correctly to H5T_NATIVE_HBOOL.
	cpp2hid = {
		{"_Bool",              "bool"},
		{"char",               "char"},
		{"unsigned char",      "unsigned char"},
		{"short",              "short"},
		{"unsigned short",     "unsigned short"},
		{"int",                "int"},
		{"unsigned int",       "unsigned int"},
		{"long",               "long"},
		{"unsigned long",      "unsigned long"},
		{"long long",          "long long"},
		{"unsigned long long", "unsigned long long"},
		{"float",              "float"},
		{"double",             "double"},
		{"long double",        "long double"},
	};
	array_type_for_var.clear();
	has_pending_record = false;
	cur_rec_fields.clear();
}

void H5Producer::record_decl_impl(const std::string& /*var*/,
                                   const std::string& name) {
	emit_record_spec();   // flush the previous struct if one is pending
	cur_rec_name      = name;
	has_pending_record = true;
}

void H5Producer::type_insert_impl(const std::string& /*var*/,
                                   const std::string& field_name,
                                   const std::string& /*record_name*/,
                                   const std::string& type) {
	cur_rec_fields.push_back({field_name, type});
}

// Arrays are handled recursively by storage_traits_t<T[N]>; no code is
// emitted here.  We just record the C++ array type string so cache_add_impl
// can later map the Clang type key to it.
void H5Producer::array_decl_impl(const std::string& var,
                                  const std::string& elem_type,
                                  uint64_t size) {
	array_type_for_var[var] = make_array_type(elem_type, size);
}

// No HID resources to release in the new engine.
void H5Producer::type_release_impl() {}

// ---------------------------------------------------------------------------
// Cache helpers
// ---------------------------------------------------------------------------

bool H5Producer::cache_add_impl(const std::string& key,
                                 const std::string& var) {
	auto it = array_type_for_var.find(var);
	if (it != array_type_for_var.end())
		// Array var -> map the Clang key to the C++ array type string.
		cpp2hid[key] = it->second;
	else
		// Record var (ct_XX) -> the Clang qualified name IS the C++ type.
		cpp2hid[key] = key;
	return true;
}

std::string H5Producer::cache_impl(const std::string& type) {
	return cpp2hid[type];
}

// ---------------------------------------------------------------------------

void H5Producer::return_type_impl(const std::string& /*var*/) {
	emit_record_spec();   // flush the last (root) struct
}

#endif



