/* Copyright (c) 2018-2026 Steven Varga, steven@vargalabs.com Toronto, ON Canada */

#pragma once

#include "producer.hpp"

#include <cstdint>
#include <map>
#include <ostream>
#include <string>
#include <vector>

enum class SqlDialect { postgres, mysql, sqlite3 };

template <SqlDialect D>
struct SqlProducer : Producer<SqlProducer<D>> {

    void file_begin_impl() {
        this->io << "-- Generated by h5cpp-compiler SQL backend\n";
        switch (D) {
            case SqlDialect::postgres: this->io << "-- Dialect: postgresql\n\n"; break;
            case SqlDialect::mysql:    this->io << "-- Dialect: mysql\n\n";     break;
            case SqlDialect::sqlite3:  this->io << "-- Dialect: sqlite3\n\n";   break;
        }
    }

    void file_end_impl() {}

    void template_decl_impl(const std::string& record,
                            const std::string& /*doc*/ = "",
                            const std::string& /*alias*/ = "",
                            const std::string& /*version*/ = "") {
        record_name = record;
    }

    void record_decl_impl(const std::string& var, const std::string& record_name) {
        if (in_record) {
            this->io << "\n);\n\n";
        }
        in_record = true;
        first_field = true;
        std::string table = sanitize_name(record_name);
        this->io << "CREATE TABLE IF NOT EXISTS ";
        quote_identifier(table);
        this->io << " (\n";
        record_type_cache[var] = nested_type();
    }

    void return_type_impl(const std::string& /*var*/) {
        if (in_record) {
            this->io << "\n);\n";
            in_record = false;
        }
    }

    void array_decl_impl(const std::string& var, const std::string& type, uint64_t /*size*/) {
        array_type_cache[var] = array_type(type);
    }

    void type_insert_impl(const std::string& /*var*/, const std::string& field_name,
                          const std::string& /*record_name*/, const std::string& type,
                          const std::string& /*on_disk_name*/ = "") {
        if (first_field) {
            first_field = false;
        } else {
            this->io << ",\n";
        }
        this->io << "    ";
        quote_identifier(field_name);
        this->io << " " << type << " NOT NULL";
    }

    void type_release_impl() {}

    void scatter_type_impl(const std::string& /*record_name*/,
                           const std::vector<typename Producer<SqlProducer>::scatter_field_t>& /*fields*/,
                           const std::string& /*chunk_size*/, const std::string& /*compress_algo*/,
                           int /*compress_level*/,
                           const std::string& /*doc*/, const std::string& /*alias*/,
                           const std::string& /*version*/, const std::string& /*on_missing*/) {}

    bool cache_add_impl(const std::string& key, const std::string& type) {
        auto it = record_type_cache.find(type);
        if (it != record_type_cache.end()) {
            type_cache[key] = it->second;
            return true;
        }
        auto it2 = array_type_cache.find(type);
        if (it2 != array_type_cache.end()) {
            type_cache[key] = it2->second;
            return true;
        }
        type_cache[key] = map_type(key);
        return true;
    }

    std::string cache_impl(const std::string& type) {
        auto it = type_cache.find(type);
        if (it != type_cache.end()) return it->second;
        return map_type(type);
    }

private:
    std::map<std::string, std::string> type_cache;
    std::map<std::string, std::string> record_type_cache;
    std::map<std::string, std::string> array_type_cache;
    std::string record_name;
    bool in_record = false;
    bool first_field = false;

    static std::string sanitize_name(const std::string& name) {
        std::string out = name;
        for (char& c : out) {
            if (c == ':') c = '_';
        }
        return out;
    }

    void quote_identifier(const std::string& name) {
        switch (D) {
            case SqlDialect::postgres:
            case SqlDialect::sqlite3:
                this->io << '"' << name << '"';
                break;
            case SqlDialect::mysql:
                this->io << '`' << name << '`';
                break;
        }
    }

    static std::string nested_type() {
        switch (D) {
            case SqlDialect::postgres: return "JSONB";
            case SqlDialect::mysql:    return "JSON";
            case SqlDialect::sqlite3:  return "TEXT";
        }
        return "TEXT";
    }

    static std::string array_type(const std::string& element_sql) {
        switch (D) {
            case SqlDialect::postgres: return element_sql + "[]";
            case SqlDialect::mysql:    return "JSON";
            case SqlDialect::sqlite3:  return "TEXT";
        }
        return "TEXT";
    }

    static std::string map_type(const std::string& type) {
        std::string primitive = map_primitive(type);
        if (!primitive.empty()) return primitive;
        return nested_type();
    }

    static std::string map_primitive(const std::string& type) {
        switch (D) {
            case SqlDialect::postgres:
                if (type == "_Bool")                return "BOOLEAN";
                if (type == "char")                 return "SMALLINT";
                if (type == "unsigned char")        return "SMALLINT";
                if (type == "short")                return "SMALLINT";
                if (type == "unsigned short")       return "SMALLINT";
                if (type == "int")                  return "INTEGER";
                if (type == "unsigned int")         return "INTEGER";
                if (type == "long")                 return "BIGINT";
                if (type == "unsigned long")        return "BIGINT";
                if (type == "long long")            return "BIGINT";
                if (type == "unsigned long long")   return "BIGINT";
                if (type == "float")                return "REAL";
                if (type == "double")               return "DOUBLE PRECISION";
                if (type == "long double")          return "DOUBLE PRECISION";
                break;
            case SqlDialect::mysql:
                if (type == "_Bool")                return "TINYINT(1)";
                if (type == "char")                 return "TINYINT";
                if (type == "unsigned char")        return "TINYINT UNSIGNED";
                if (type == "short")                return "SMALLINT";
                if (type == "unsigned short")       return "SMALLINT UNSIGNED";
                if (type == "int")                  return "INT";
                if (type == "unsigned int")         return "INT UNSIGNED";
                if (type == "long")                 return "BIGINT";
                if (type == "unsigned long")        return "BIGINT UNSIGNED";
                if (type == "long long")            return "BIGINT";
                if (type == "unsigned long long")   return "BIGINT UNSIGNED";
                if (type == "float")                return "FLOAT";
                if (type == "double")               return "DOUBLE";
                if (type == "long double")          return "DOUBLE";
                break;
            case SqlDialect::sqlite3:
                if (type == "_Bool")                return "INTEGER";
                if (type == "char")                 return "INTEGER";
                if (type == "unsigned char")        return "INTEGER";
                if (type == "short")                return "INTEGER";
                if (type == "unsigned short")       return "INTEGER";
                if (type == "int")                  return "INTEGER";
                if (type == "unsigned int")         return "INTEGER";
                if (type == "long")                 return "INTEGER";
                if (type == "unsigned long")        return "INTEGER";
                if (type == "long long")            return "INTEGER";
                if (type == "unsigned long long")   return "INTEGER";
                if (type == "float")                return "REAL";
                if (type == "double")               return "REAL";
                if (type == "long double")          return "REAL";
                break;
        }
        return {};
    }
};
