/* Copyright (c) 2018-2026 Steven Varga, steven@vargalabs.com Toronto, ON Canada */

#pragma once

#include "producer.hpp"

#include <cstdint>
#include <map>
#include <ostream>
#include <string>
#include <utility>
#include <vector>

// Tier-1 backend for vargalabs/sandbox/pb.hpp. Emits:
//   template<> struct pb::meta::descriptor_t<T> {
//       static constexpr auto fields = std::tuple{
//           pb::field<N, &T::m>{}, ...
//       };
//   };
// One specialization per encountered record type, in topological order
// (nested types before outer types). Field numbers come from per-field
// [[clang::annotate("pb::field=N")]] attributes — the consumer (consumer_pb.hpp)
// parses the annotations and supplies N to type_insert.
struct PbProducer : Producer<PbProducer> {

    void file_begin_impl(){
        io << "/* Generated by h5cpp-compiler --protocol-buffers. Do not edit. */\n";
        io << "#pragma once\n\n";
        io << "#include <pb.hpp>\n\n";
    }

    void file_end_impl(){
        io << "\n";
    }

    // template_decl is the per-record opener. `record` is the qualified type
    // name (e.g. "::sn::sensor::reading_t"). Each record's descriptor_t is a
    // standalone specialization at file scope.
    void template_decl_impl(const std::string& record){
        record_name = record;
        first_field = true;
        io << "template<> struct pb::meta::descriptor_t<" << record << "> {\n";
        io << "    static constexpr auto fields = std::tuple{";
    }

    // record_decl is called for each topologically-prior record (nested
    // types). For PbProducer we don't emit nested compound declarations —
    // nested message types get their OWN descriptor_t specialization in a
    // prior pass. The variable name is unused in pb output but tracked for
    // the cache contract.
    void record_decl_impl(const std::string& var, const std::string& /*record_name*/){
        (void)var;
        // no-op for pb; nested messages reference their own descriptor_t<T>
    }

    // array_decl: C arrays (T[N]) don't have a clean proto3 wire mapping.
    // Stage 1 refuses; users must use std::vector<T> (FR3 repeated) or
    // std::array<T,N> (planned future).
    void array_decl_impl(const std::string& var, const std::string& /*type*/, uint64_t /*size*/){
        (void)var;
        io << "\n    // ERROR: C arrays not supported by pb backend (use std::vector<T> instead)";
    }

    // type_insert: emit one pb::field<N, &Record::member>{} entry.
    // `var` is overloaded by the consumer to carry the field number as a
    // decimal string ("1", "2", ...) instead of the HDF5 vname. record_name
    // is the qualified record type; field_name is the member identifier.
    void type_insert_impl(const std::string& var, const std::string& field_name,
                          const std::string& rec_name, const std::string& /*type*/){
        if (!first_field) io << ",";
        io << "\n        pb::field<" << var << ", &" << rec_name << "::" << field_name << ">{}";
        first_field = false;
    }

    void return_type_impl(const std::string& /*var*/){
        io << "\n    };\n};\n\n";
    }

    void type_release_impl(){
        // pb has no resource-id lifetime to manage — descriptor_t entries are
        // pure compile-time. No-op.
    }

    // The cache contract is HDF5-shaped (cpp-type → hid_t-var mapping).
    // PbProducer doesn't need that vocabulary — pb dispatches via traits at
    // the library level, not via per-type variable aliases. Implement as
    // identity stubs so the existing consumer driver still compiles.
    bool cache_add_impl(const std::string& /*key*/, const std::string& /*type*/){ return true; }
    std::string cache_impl(const std::string& type){ return type; }

    // FR6/stage 4: oneof emission. Called directly by PbTemplateCallback for
    // std::variant member fields (not via the CRTP Producer<> hook surface,
    // which is HDF5-shaped). Emits a pb::oneof<&R::m, pb::alt<T1,N1>,...>{}
    // entry in the descriptor's fields tuple.
    void emit_oneof(const std::string& member_name,
                    const std::string& record_name,
                    const std::vector<std::string>& alt_types,
                    const std::vector<std::uint32_t>& tags){
        if (!first_field) io << ",";
        io << "\n        pb::oneof<&" << record_name << "::" << member_name;
        for (std::size_t i = 0; i < alt_types.size(); ++i) {
            io << ", pb::alt<" << alt_types[i] << ", " << tags[i] << ">";
        }
        io << ">{}";
        first_field = false;
    }

    // Stage 5: wire-spec annotation. Same shape as type_insert but emits an
    // explicit WireSpec template arg on pb::field<N, Ptr, WireSpec>. Called
    // when the consumer sees a [[clang::annotate("pb::wire=spec")]] attribute
    // on a field. wire_spec is the spec name without the `_t` suffix, e.g.
    // "sint32", "fixed64", "sfixed32".
    void emit_field_with_spec(std::uint32_t tag,
                              const std::string& field_name,
                              const std::string& record_name,
                              const std::string& wire_spec){
        if (!first_field) io << ",";
        io << "\n        pb::field<" << tag
           << ", &" << record_name << "::" << field_name
           << ", pb::wire::" << wire_spec << "_t>{}";
        first_field = false;
    }

    // Stage 6 (Tier 4): adapter_field emission. Called when the consumer
    // sees a [[clang::annotate("pb::adapter=Name")]] attribute on a field.
    // Name is the adapter shorthand ("Timestamp", "Duration"), which maps
    // to the library symbol pb::Name_adapter (Timestamp_adapter, etc.).
    void emit_adapter_field(std::uint32_t tag,
                             const std::string& field_name,
                             const std::string& record_name,
                             const std::string& adapter_name){
        if (!first_field) io << ",";
        io << "\n        pb::adapter_field<" << tag
           << ", &" << record_name << "::" << field_name
           << ", pb::" << adapter_name << "_adapter>{}";
        first_field = false;
    }

private:
    std::string record_name;
    bool        first_field = true;
};
